### ISSUE TITLE
<FEATURE> Add Lightning-JS CLI tool

### ISSUE THREAD

**Issue by FadTheChad** [TeamNorden/Lightning#1]
Basically what this will be able to do is that the user can install lightning's CLI tool in order to generate a template to work on

Will look more into this after the base lib is done

**Comment by FadTheChad** [comment]
Started Looking into this

Gonna use yargs for it and for now, 3 commands and 2 sub commands are planned

Thats all im gonna reveal for now :)

**Comment by Codeize** [comment]
See https://github.com/TeamNorden/Lightning-CLI
